_v = 1

locale {
  fallback = "en_us"
}
optimization {
  cache-plugin-class = true
  disable-data-fixer = false
  goal-selector-update-interval = 3
  use-activation-and-tracking-range = true
  nearby-player-index-enabled = true
  nearby-player-index-verify = false
  optimize-powered-rails = true
  memory-cache-cleanup-enabled = false
  memory-cache-cleanup-interval = 300
  memory-cache-cleanup-targets = []
  network-optimization-enabled = false
  network-optimization-netty-threads = 0
  disable-entity-collisions = false
}
compatibility {
  material-property-overrides {
  }
  entity-property-overrides {
  }
  symlink-world = false
  extra-logic-worlds = [
    "com.example.mod.ExtraLogicWorld",
    "xyz.nucleoid.fantasy.RuntimeWorld"
  ]
  forward-permission = true
  valid-username-regex = ""
  isolate-plugin-class-loaders = [
    "com.example.mod.package.aaaa"
  ]
  isolate-adventure-from-modloader = false
}
async-catcher {
  dump = true
  warn = true
  defaultOperation = block
  overrides {
  }
}
velocity {
  enable = false
  secret = ""
}
experimental {
  replaceable-base-world-generator = false
}